//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarExhibitionEntities : DbContext
    {
        public CarExhibitionEntities()
            : base("name=CarExhibitionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Login> T_Login { get; set; }
        public virtual DbSet<T_NewCarArrival> T_NewCarArrival { get; set; }
        public virtual DbSet<T_SellCar> T_SellCar { get; set; }
        public virtual DbSet<T_Request> T_Request { get; set; }
    }
}
