//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Request
    {
        public int id { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public string system { get; set; }
        public string user { get; set; }
        public string tip { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string sookht { get; set; }
        public string name { get; set; }
        public string codemeli { get; set; }
        public string tamas { get; set; }
        public string email { get; set; }
        public string adrees { get; set; }
    }
}
