//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SellCar
    {
        public int id { get; set; }
        public string moshincode { get; set; }
        public string Type1 { get; set; }
        public string System { get; set; }
        public string User { get; set; }
        public string Style { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Fuel { get; set; }
        public string Country { get; set; }
        public string Capacity { get; set; }
        public string vin { get; set; }
        public string engineNumber { get; set; }
        public string PlaqueNumber { get; set; }
        public string BodyNumber { get; set; }
        public string NumberOfCylinders { get; set; }
        public string NumberOfAxes { get; set; }
        public string Accessories { get; set; }
        public string MachineConDition { get; set; }
        public string Insurance { get; set; }
        public string Violation { get; set; }
        public string TLApproval { get; set; }
        public string madarek { get; set; }
        public string pprice { get; set; }
        public string ppricematn { get; set; }
        public string EmailOwner { get; set; }
        public string CarOwner { get; set; }
        public string IdentificationCode { get; set; }
        public string FixedNumber { get; set; }
        public string sellname { get; set; }
        public string sellemail { get; set; }
        public string sellmobile { get; set; }
        public string sellcodemeli { get; set; }
        public string Price { get; set; }
        public string pricematn { get; set; }
        public string TransactionDate { get; set; }
    }
}
